import { StyleSheet } from 'react-native';
import { s } from '../../../theme/responsive';
const styles = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: 'transparent',
        paddingHorizontal: s(16),
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: s(12),
    },
    title: {
        color: '#111827',
        fontSize: 20,
        fontWeight: '400',
    },
    content: {
        paddingTop: s(24),
    },
    avatarCard: {
        alignItems: 'center',
        borderRadius: 18,
        backgroundColor: '#ffffff',
        padding: s(24),
        marginTop: s(28),
    },
    avatarWrap: {
        position: 'relative',
        width: 148,
        height: 148,
    },
    avatar: {
        width: 148,
        height: 148,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 3,
        borderColor: '#7dd3fc',
        borderRadius: 100,
        backgroundColor: '#ecfeff',
        overflow: 'hidden',
    },
    avatarImage: {
        width: '100%',
        height: '100%',
    },
    cameraButton: {
        position: 'absolute',
        right: s(-16),
        bottom: s(-4),
        width: 44,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 3,
        borderRadius: 21,
        backgroundColor: '#121414',
    },
    formCard: {
        borderRadius: 18,
        backgroundColor: '#ffffff',
        marginTop: s(18),
        padding: s(16),
        gap: s(14),
    },
    inputGroup: {
        gap: s(7),
    },
    inputLabel: {
        color: '#94a3b8',
        fontSize: 12,
        fontWeight: '800',
    },
    inputRow: {
        minHeight: 50,
        flexDirection: 'row',
        alignItems: 'center',
        gap: s(12),
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 14,
        backgroundColor: '#ecfeff',
        paddingHorizontal: s(14),
    },
    input: {
        flex: 1,
        color: '#111827',
        fontSize: 15,
        fontWeight: '400',
        paddingVertical: 0,
    },
    dateInputText: {
        lineHeight: 22,
    },
    modalOverlay: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(15, 23, 42, 0.42)',
        paddingHorizontal: s(24),
    },
    modalCard: {
        width: '100%',
        borderRadius: 18,
        backgroundColor: '#ffffff',
        padding: s(18),
    },
    modalTitle: {
        color: '#111827',
        fontSize: 18,
        fontWeight: '700',
        textAlign: 'center',
    },
    datePickerColumns: {
        flexDirection: 'row',
        gap: s(10),
        marginTop: s(18),
    },
    dateColumn: {
        flex: 1,
        alignItems: 'center',
        gap: s(10),
    },
    dateLabel: {
        color: '#94a3b8',
        fontSize: 12,
        fontWeight: '800',
    },
    dateStepButton: {
        width: '100%',
        minHeight: 38,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 12,
    },
    dateValue: {
        color: '#111827',
        fontSize: 17,
        fontWeight: '700',
    },
    modalActions: {
        flexDirection: 'row',
        gap: s(12),
        marginTop: s(22),
    },
    modalButton: {
        flex: 1,
        minHeight: 44,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 12,
    },
    modalButtonText: {
        color: '#111827',
        fontSize: 14,
        fontWeight: '800',
    },
    modalDoneText: {
        color: '#ffffff',
        fontSize: 14,
        fontWeight: '900',
    },
});
export default styles;
