import { StyleSheet } from "react-native";
import { s } from '../../../theme/responsive';
const styles = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: 'transparent',
    },
    scrollContent: {
        paddingHorizontal: s(16),
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: s(12),
    },
    title: {
        color: '#111827',
        fontSize: 22,
        fontWeight: '400',
    },
    editButton: {
        height: 38,
        flexDirection: 'row',
        alignItems: 'center',
        gap: s(8),
        borderWidth: 1,
        borderRadius: 19,
        backgroundColor: '#ccfbf1',
        paddingHorizontal: s(14),
    },
    editText: {
        color: '#0f766e',
        fontSize: 14,
        fontWeight: '900',
    },
    profileCard: {
        alignItems: 'center',
        borderRadius: 18,
        backgroundColor: '#ffffff',
        marginTop: s(24),
        paddingHorizontal: 0,
        paddingTop: s(24),
        paddingBottom: s(24),
    },
    coverWrap: {
        width: '100%',
        height: 140,
        borderTopLeftRadius: 18,
        borderTopRightRadius: 18,
        overflow: 'hidden',
    },
    coverImage: {
        width: '100%',
        height: '100%',
    },
    avatarWrap: {
        width: 104,
        height: 104,
        marginTop: s(-52),
    },
    avatarWrapNoCover: {
        marginTop: 0,
    },
    avatar: {
        width: 148,
        height: 148,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 3,
        borderColor: '#7dd3fc',
        borderRadius: 100,
        backgroundColor: '#ecfeff',
        overflow: 'hidden',
    },
    avatarImage: {
        width: '100%',
        height: '100%',
    },
    name: {
        color: '#111827',
        fontSize: 28,
        fontWeight: '400',
        marginTop: s(16),
    },
    subtitle: {
        color: '#64748b',
        fontSize: 13,
        fontWeight: '400',
        marginTop: s(5),
    },
    progressCard: {
        borderRadius: 18,
        borderWidth: 1,
        backgroundColor: '#ffffff',
        marginTop: s(14),
        paddingHorizontal: s(16),
        paddingVertical: s(14),
    },
    progressHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    progressTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: s(8),
    },
    progressTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#111827',
    },
    progressBadge: {
        paddingHorizontal: s(10),
        paddingVertical: s(4),
        borderRadius: 10,
        backgroundColor: '#ecfeff',
    },
    progressBadgeText: {
        fontSize: 12,
        fontWeight: '800',
    },
    progressSubRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: s(8),
        marginTop: s(6),
    },
    progressPercent: {
        fontSize: 13,
        fontWeight: '800',
    },
    progressSubText: {
        fontSize: 11,
        fontWeight: '500',
        flex: 1,
    },
    progressTrack: {
        height: 8,
        borderRadius: 8,
        overflow: 'hidden',
        marginTop: s(10),
        backgroundColor: '#e5e7eb',
    },
    progressFill: {
        height: '100%',
        borderRadius: 8,
    },
    progressFieldsRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: s(10),
        marginTop: s(12),
    },
    progressFieldItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: s(6),
    },
    progressDot: {
        width: 16,
        height: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    progressFieldLabel: {
        fontSize: 11,
        fontWeight: '600',
    },
    progressCta: {
        marginTop: s(10),
        alignSelf: 'flex-start',
    },
    progressCtaText: {
        fontSize: 12,
        fontWeight: '700',
    },
    switchAccountButton: {
        minHeight: 70,
        flexDirection: 'row',
        alignItems: 'center',
        gap: s(14),
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 16,
        backgroundColor: '#ffffff',
        marginTop: s(14),
        paddingHorizontal: s(16),
        paddingVertical: s(14),
    },
    switchAccountIcon: {
        width: 42,
        height: 42,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 12,
        backgroundColor: '#ecfeff',
    },
    switchAccountCopy: {
        flex: 1,
    },
    switchAccountTitle: {
        color: '#111827',
        fontSize: 15,
        fontWeight: '500',
    },
    switchAccountSubtitle: {
        color: '#94a3b8',
        fontSize: 12,
        fontWeight: '600',
        marginTop: s(4),
    },
    detailsCard: {
        borderRadius: 18,
        backgroundColor: '#ffffff',
        marginTop: s(18),
        paddingHorizontal: s(16),
        paddingTop: s(18),
    },
    addressCard: {
        minHeight: 74,
        flexDirection: 'row',
        alignItems: 'center',
        gap: s(14),
        borderRadius: 18,
        backgroundColor: '#ffffff',
        marginTop: s(18),
        paddingHorizontal: s(16),
        paddingVertical: s(16),
    },
    sectionTitle: {
        color: '#64748b',
        fontSize: 16,
        fontWeight: '400',
        marginBottom: s(2),
    },
    logoutButton: {
        height: 50,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: s(10),
        borderRadius: 34,
        // backgroundColor: '#e8c96a',
        marginTop: s(36),
    },
    logoutText: {
        // color: '#000',
        fontSize: 16,
        fontWeight: '500',
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: s(14),
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
        paddingVertical: s(16),
    },
    detailIcon: {
        width: 42,
        height: 42,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 12,
        backgroundColor: '#ecfeff',
    },
    detailCopy: {
        flex: 1,
    },
    detailLabel: {
        color: '#94a3b8',
        fontSize: 12,
        fontWeight: '500',
    },
    detailValue: {
        color: '#111827',
        fontSize: 15,
        fontWeight: '400',
        marginTop: s(4),
    },
    emailDropdown: {
        borderWidth: 1,
        borderRadius: 12,
        marginTop: s(4),
        marginBottom: s(6),
        overflow: 'hidden',
    },
    emailDropdownItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: s(14),
        paddingVertical: s(12),
    },
    emailDropdownLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: s(14),
    },
    emailDropdownValue: {
        fontSize: 14,
        fontWeight: '400',
    },
    emailDropdownBadge: {
        fontSize: 10,
        fontWeight: '700',
        paddingHorizontal: s(7),
        paddingVertical: s(2),
        borderRadius: 6,
        overflow: 'hidden',
    },
    emailDropdownAdd: {
        width: 26,
        height: 26,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 13,
    },
    emailDropdownRight: {
        alignItems: 'center',
        gap: s(6),
    },
    emailDropdownPrimaryLabel: {
        fontSize: 10,
        fontWeight: '700',
        color: '#ffffff',
        backgroundColor: '#dc2626',
        paddingHorizontal: s(6),
        paddingVertical: s(2),
        borderRadius: 4,
        overflow: 'hidden',
    },
    emailInputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: s(8),
        paddingHorizontal: s(14),
        paddingVertical: s(10),
    },
    emailEditRow: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: s(8),
    },
    emailInput: {
        flex: 1,
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: s(10),
        paddingVertical: s(8),
        fontSize: 14,
    },
    emailInputSubmit: {
        width: 28,
        height: 28,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 17,
    },
    emailInputClose: {
        width: 28,
        height: 28,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 17,
        borderWidth: 1,
    },
    versionText: {
        color: '#94a3b8',
        fontSize: 12,
        fontWeight: '700',
        marginTop: s(18),
        textAlign: 'center',
    },
    switchSheetOverlay: {
        flex: 1,
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(0, 0, 0, 0.42)',
    },
    switchSheet: {
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingHorizontal: s(16),
        paddingTop: s(10),
        paddingBottom: s(20),
    },
    switchSheetHandle: {
        width: 44,
        height: 4,
        alignSelf: 'center',
        borderRadius: 3,
        backgroundColor: '#d1d5db',
        marginBottom: s(16),
    },
    switchSheetAccountBox: {
        borderWidth: 1,
        borderRadius: 16,
        paddingHorizontal: s(12),
        paddingVertical: s(12),
    },
    switchSheetAccountRow: {
        minHeight: 46,
        flexDirection: 'row',
        alignItems: 'center',
        gap: s(10),
    },
    switchSheetAvatar: {
        width: 38,
        height: 38,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 19,
        backgroundColor: '#ecfeff',
        overflow: 'hidden',
    },
    switchSheetAvatarImage: {
        width: '100%',
        height: '100%',
    },
    switchSheetAccountName: {
        flex: 1,
        fontSize: 15,
        fontWeight: '400',
    },
    switchSheetAddRow: {
        minHeight: 48,
        flexDirection: 'row',
        alignItems: 'center',
        gap: s(11),
        marginTop: s(12),
    },
    switchSheetAddIcon: {
        width: 38,
        height: 38,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 19,
        backgroundColor: '#071116',
    },
    switchSheetAddText: {
        flex: 1,
        fontSize: 15,
        fontWeight: '400',
    },
    metaText: {
        fontSize: 14,
        fontWeight: '700',
        marginTop: s(16),
        textAlign: 'center',
    },
});
export default styles;
