import { StyleSheet } from "react-native";
import { font } from "../../../../theme/typography";
export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 14,
        paddingTop: 0,
        paddingBottom: 8,
        borderBottomWidth: 1,
        gap: 12,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    headerTitle: {
        fontSize: font.xl,
        fontWeight: '500',
    },
    profileCard: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 8,
        paddingVertical: 6,
        gap: 6,
    },
    avatar: {
        width: 28,
        height: 28,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatarText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: font.sm,
    },
    profileEmail: {
        fontSize: font.sm,
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingTop: 20,
        paddingBottom: 30,
    },
    stepHeader: {
        marginBottom: 20,
    },
    stepLabel: {
        fontSize: font.lg,
        fontWeight: '600',
        letterSpacing: 0.5,
        textTransform: 'none',
    },
    backLink: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginBottom: 12,
    },
    backLinkText: {
        fontSize: font.base,
        fontWeight: '500',
    },
    section: {
        marginBottom: 24,
    },
    sectionTitle: {
        fontSize: font.lg,
        fontWeight: '600',
        marginBottom: 12,
    },
    urgencyGrid: {
        flexDirection: 'row',
        gap: 10,
    },
    urgencyButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1.5,
        borderRadius: 10,
        paddingVertical: 12,
        gap: 8,
    },
    urgencyDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    urgencyLabel: {
        fontSize: font.base,
        fontWeight: '600',
    },
    categoriesGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 6,
    },
    categoryCard: {
        width: '23%',
        borderWidth: 1.5,
        borderRadius: 8,
        padding: 7,
        alignItems: 'center',
    },
    categoryIcon: {
        width: 26,
        height: 26,
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 4,
    },
    categoryTitle: {
        fontSize: font.xs,
        fontWeight: '700',
        textAlign: 'center',
        marginBottom: 2,
    },
    categoryFields: {
        fontSize: font.xs,
        fontWeight: '600',
        marginBottom: 2,
    },
    nextButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        paddingVertical: 14,
        marginTop: 20,
        gap: 8,
    },
    nextButtonText: {
        color: '#fff',
        fontSize: font.lg,
        fontWeight: '600',
    },
    selectedList: {
        gap: 10,
    },
    selectedItem: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        gap: 12,
    },
    selectedItemName: {
        fontSize: font.md,
        fontWeight: '600',
    },
    selectedItemMeta: {
        fontSize: font.sm,
        marginTop: 2,
    },
    fieldsList: {
        gap: 10,
    },
    fieldItem: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 12,
        gap: 12,
    },
    checkbox: {
        width: 18,
        height: 18,
        borderWidth: 1.5,
        borderRadius: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    fieldLabel: {
        fontSize: font.md,
        fontWeight: '500',
    },
    submitButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        paddingVertical: 14,
        marginTop: 20,
        gap: 8,
    },
    submitButtonText: {
        color: '#fff',
        fontSize: font.lg,
        fontWeight: '600',
    },
    formGroup: {
        marginBottom: 14,
    },
    label: {
        fontSize: font.sm,
        fontWeight: '600',
        marginBottom: 6,
    },
    dropdown: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
    },
    dropdownText: {
        fontSize: font.base,
        fontWeight: '500',
    },
    input: {
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: font.base,
    },
    dateField: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
    },
    dateText: {
        fontSize: font.base,
        fontWeight: '500',
    },
    feedbackBox: {
        flexDirection: 'row',
        borderWidth: 1,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 12,
        gap: 10,
        marginBottom: 20,
        alignItems: 'flex-start',
    },
    feedbackIcon: {
        marginTop: 2,
    },
    feedbackTitle: {
        fontSize: font.base,
        fontWeight: '600',
        marginBottom: 4,
    },
    feedbackText: {
        fontSize: font.sm,
        lineHeight: 15,
    },
    timelineHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    refreshBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderRadius: 6,
        paddingHorizontal: 8,
        paddingVertical: 6,
        gap: 4,
    },
    refreshText: {
        fontSize: font.sm,
        fontWeight: '600',
    },
    timelineNote: {
        fontSize: font.sm,
        marginBottom: 12,
        lineHeight: 15,
    },
    statusBadges: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 14,
        flexWrap: 'wrap',
    },
    badge: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderRadius: 6,
        paddingHorizontal: 8,
        paddingVertical: 5,
        gap: 4,
    },
    badgeText: {
        fontSize: font.sm,
        fontWeight: '600',
    },
    timelineItems: {
        gap: 10,
    },
    timelineItem: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        gap: 10,
    },
    itemName: {
        fontSize: font.base,
        fontWeight: '600',
    },
    statusBadge: {
        borderWidth: 1,
        borderRadius: 6,
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    statusText: {
        fontSize: font.sm,
        fontWeight: '600',
    },
    auditNote: {
        fontSize: font.sm,
        marginBottom: 12,
        lineHeight: 15,
    },
    auditItem: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 12,
        gap: 10,
        marginBottom: 12,
    },
    auditTitle: {
        fontSize: font.base,
        fontWeight: '600',
        marginBottom: 2,
    },
    auditDesc: {
        fontSize: font.sm,
    },
    auditFooter: {
        fontSize: font.sm,
        lineHeight: 14,
    },
});
