# Project-wide Gradle settings.

# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# Enable Parallel Build (Isse aapke CPU par build thodi fast banegi)
org.gradle.parallel=true

# AndroidX support
android.useAndroidX=true

# ALL Architectures (Ise comment kar diya hai taaki saari required libraries include ho sakein)
# reactNativeArchitectures=arm64-v8a,armeabi-v7a,x86,x86_64

# Use New Architecture (i3 Processor ke liye disabled hi rakhein)
# newArchEnabled=false

# Use Hermes Engine (Ise MUST TRUE rakhna hai)
hermesEnabled=true

# Edge-to-edge support
edgeToEdgeEnabled=false

# Architectures for Production Release
reactNativeArchitectures=arm64-v8a,armeabi-v7a,x86,x86_64

MYAPP_UPLOAD_STORE_FILE=my-upload-key.keystore
MYAPP_UPLOAD_KEY_ALIAS=my-key-alias
MYAPP_UPLOAD_STORE_PASSWORD=companyvista$#26
MYAPP_UPLOAD_KEY_PASSWORD=companyvista$#26